name: us-stock-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - pip:
    # Portfolio optimization
    - PyPortfolioOpt==1.5.5

    # Machine learning
    - xgboost>=1.7.0
    - mlflow>=2.8.0

    # Data & analysis
    - yfinance>=0.2.28
    - pyarrow>=13.0.0
    - fastparquet>=2023.7.0
    - lxml>=4.9.0

    # Backtesting
    - backtrader>=1.9.78

    # Optimization
    - optuna>=3.3.0

    # Visualization
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - plotly>=5.16.0

    # Configuration
    - pyyaml>=6.0

    # Web dashboard (Phase 2)
    - fastapi>=0.103.0
    - uvicorn[standard]>=0.23.0
    - streamlit>=1.27.0
    - websockets>=11.0
    - python-multipart>=0.0.6
    - aiofiles>=23.0.0

    # Database
    - sqlalchemy>=2.0.0
    - alembic>=1.12.0

    # Utilities
    - python-dotenv>=1.0.0
    - tqdm>=4.66.0
    - loguru>=0.7.0

    # Testing
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - pytest-asyncio>=0.21.0

    # Jupyter
    - jupyter>=1.0.0
    - ipykernel>=6.25.0
    - ipywidgets>=8.1.0
